### PR TITLE
refactor: remove deprecated `prettier` property

### LINKED ISSUE #267: `jsxBracketSameLine` is deprecated

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #267.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
@joshua-mo-143 is there anything I can do to get this merged?

**Comment by joshua-mo-143** [comment]
> @joshua-mo-143 is there anything I can do to get this merged?

Hey Hamir, apologies for the late response!

I'll ask about this internally to see if we can get this merged as this as been open for a while and we should really avoid using deprecated properties if possible.

**Comment by joshua-mo-143** [comment]
It looks like `jsxBracketSameLine` has been replaced by `bracketSameLine` - would you be able to add this change?

Ref this blog post by Prettier: https://prettier.io/blog/2021/09/09/2.4.0.html

**Comment by hamirmahal** [comment]
@joshua-mo-143 I updated it so that it uses `bracketSameLine` instead of `jsxBracketSameLine`.

**Review by GugaGongadze — APPROVED** [review]

**Comment by joshua-mo-143** [comment]
Finally managed to get this over the line. Thanks for contributing @hamirmahal !

**Comment by hamirmahal** [comment]
You're welcome, @joshua-mo-143!

**Pull request merged**
