### PR TITLE
fix: file formatting inconsistencies

### LINKED ISSUE #262: js, jsx, ts, json, and md files have formatting inconsistencies

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #262.

### CODE REVIEW

**Comment by hamirmahal** [comment]
I deliberately left out formatting for `.tsx` files because that would include `diff`s like this one, which I think would be significantly more work for the team to review.

image

**Comment by hamirmahal** [comment]
I deliberately left out formatting for `.tsx` files because that would include several `diff`s like this one, which I think would be significantly more work for the team to review.

image

**Review by chesedo — APPROVED** [review]
Thanks for this @hamirmahal

**Comment by hamirmahal** [comment]
You're welcome, @chesedo.

**Pull request merged**
